### ISSUE TITLE
Type error on first npm start

### ISSUE THREAD

**Issue by stevekrouse** [funkia/turbine-starter#2]
Hello, you may recall me from [this pull req](https://github.com/funkia/turbine/pull/74)

I first tried to get this starter kit working on codesandbox.io but it didn't work for some reason but it was failing silently so I couldn't figure it out.

I moved to my usual dev environment of cloud 9 next. I cloned the repo as it said and then started the server and got a bunch of type errors.

```
> turbine-starter@0.0.1 start /home/ubuntu/workspace/my-turbine-project
> webpack-dev-server --open

Project is running at http://localhost:8080/
webpack output is served from /
webpack: wait until bundle finished: /

[at-loader] Using typescript@2.9.2 from typescript and "tsconfig.json" from /home/ubuntu/workspace/my-turbine-project/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
Hash: 442d713a704781aedde2
Version: webpack 3.9.1
Time: 4779ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  598 kB       0  [emitted]  [big]  main
  [11] ./node_modules/@funkia/hareactive/dist/es/index.js 372 bytes {0} [built]
  [14] ./node_modules/@funkia/hareactive/dist/es/common.js 4.01 kB {0} [built]
  [48] multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.ts 40 bytes {0} [built]
  [49] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
  [50] ./node_modules/url/url.js 23.3 kB {0} [built]
  [57] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [59] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [60] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [62] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [67] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [69] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [71] ./src/index.ts 997 bytes {0} [built]
  [72] ./node_modules/@funkia/jabz/dist/es/index.js 520 bytes {0} [built]
  [79] ./node_modules/@funkia/jabz/dist/es/writer.js 1.07 kB {0} [built]
  [80] ./node_modules/@funkia/turbine/dist/es6/index.js 194 bytes {0} [built]
    + 86 hidden modules

ERROR in [at-loader] ./src/index.ts:33:41
    TS2345: Argument of type '({ count }: ViewInput) => Component<Merge<Merge<Remap<Merge<DefaultOutput> | Merge<BehaviorOutput...' is not assignable to parameter of type 'View1<ViewInput, ModelInput, {}>'.
  Type 'Component<Merge<Merge<Remap<Merge<DefaultOutput> | Merge<BehaviorOutput<any> & DefaultOutput> | M...' is not assignable to type 'Child<ModelInput>'.
    Type 'Component<Merge<Merge<Remap<Merge<DefaultOutput> | Merge<BehaviorOutput<any> & DefaultOutput> | M...' is not assignable to type 'Component<ModelInput, any>'.
      Type 'Merge<Merge<Remap<Merge<DefaultOutput> | Merge<BehaviorOutput<any> & DefaultOutput> | Merge<Outpu...' is not assignable to type 'ModelInput'.
        Property 'increment' is missing in type 'Merge<Merge<Remap<Merge<DefaultOutput> | Merge<BehaviorOutput<any> & DefaultOutput> | Merge<Outpu...'.
webpack: Failed to compile.
```

I even made a video of my experience for my extra colour: https://www.useloom.com/share/b5fe536693ba4e44a7fa20cf95928c55

I'd really appreciate your help getting up and running here. I'm very excited to play around with this framework.

**Comment by limemloh** [comment]
When I run the exact same commands on my own computer it works without any errors.

But I noticed that your output is claiming to use typescript@2.9.2, and turbine-starter have typescript@2.7.2 as a dependency, which might be the problem.

So I have updated all the dependencies of turbine-starter cbb5b9a and I hope this fixes it.

**Comment by stevekrouse** [comment]
Thanks for your help! The new commit you created still failed for me, but it worked when I set it to `"typescript": "2.9.2",`. Wacky

**Comment by paldepind** [comment]
TypeScript makes breaking changes between releases. So if you had another `typescript` version than `2.9.2` specified then that is likely to cause trouble.

I've just released a new version of Turbine which works with the latest version of TypeScript and updated turbine-starter to this version of Turbine. In other words the code in turbine starter should now work with the latest TypeScript version.

**Comment by stevekrouse** [comment]
Awesome, thanks! It compiled with no error once I fixed what looks like a small typo https://github.com/funkia/turbine-starter/pull/3

For posterity, here's the start script that worked for me on cloud9:

`"start": "webpack-dev-server --port $PORT --host $IP --public $C9_HOSTNAME",`

Now my issues are:

1. This only seems to work if I leave the chrome console open. Maybe it has to do with disabling the cache? Have you heard of this error before? If I leave it closed, it doesn't update the page, even if I restart the server!

2. Hot reloading doesn't work, even for small changes. It always reloads the entire page. Is that the behavior you get as well?
